version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: panel_profits
      POSTGRES_USER: panel_profits_user
      POSTGRES_PASSWORD: secure_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: